### ISSUE TITLE
NoInfoAvailableException when trying to investigate a restricted user

### ISSUE THREAD

**Issue by myangelaku** [circleguard/circleguard#121] opened 2021-01-04 15:06 UTC
Circlegua rd also just stops so I'd suggest to just skip those instead. Also maybe a nicer error message.

```
[ERROR] 2021/01/04 16:03:16.0785 Error while running circlecore. Please report this to the developers through discord or github.
 (circleguard_gui, main_tab.py:526)
Traceback (most recent call last):
  File "gui\main_tab.py", line 308, in run_circleguard
  File "site-packages\circleguard\circleguard.py", line 477, in load_info
  File "site-packages\circleguard\loadables.py", line 140, in load_info
  File "site-packages\circleguard\loadables.py", line 329, in load_info
  File "site-packages\circleguard\loader.py", line 124, in wrapper
  File "site-packages\circleguard\loader.py", line 349, in get_user_best
  File "site-packages\circleguard\loader.py", line 610, in check_response
circleguard.loader.NoInfoAvailableException: No info was available from the api for the given arguments.
```

**Comment by tybug** [comment] 2021-01-07 18:03
duplicate of #113?

**Closed by tybug** 2021-01-07 18:03 UTC
