### ISSUE TITLE
Random red text appears in INFO box

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#138] opened 2021-03-30 18:00 UTC
Sometimes it red AFTER loading replays, but sometimes it appears WHILE loading replays...
![Screenshot_39](https://user-images.githubusercontent.com/75766843/113034008-4f846580-919a-11eb-9976-3e94665d9868.png)
I would say, before all those ratelimits, there is was a lot of "Replay not available", but I thought that the bug occurs right after this text, like for example here ...
![Screenshot_40](https://user-images.githubusercontent.com/75766843/113034561-e5b88b80-919a-11eb-8819-e4daa6eef004.png)
I dont know if this reproduceable, but it was 12 loadables (for HD/HR/HDHR/DT/NC/HDDT/HDNC/DTHR/NCHR/HDDTHR/HDNCHR and blank) on 983680 (first screenshot) and 519080 (second screenshot)

**Comment by myangelaku** [comment] 2021-03-30 18:01
If I recall correctly, this happened to me a few times as well.

**Comment by tybug** [comment] 2021-03-30 18:14
I wish I was able to reproduce this, it happened to me once or twice in a dev setup then never again. I'll give it another shot.

**Comment by tybug** [comment] 2021-03-30 19:02
Could be, but that doesn't explain why only a single "ratelimited" message was colored red, and I also don't think we end with a div anywhere else in our code (though I could be wrong on that).

**Comment by tybug** [comment] 2021-04-12 17:04
recording all occurrences of this here in hopes that a pattern jumps out because I've got nothing

![image](https://user-images.githubusercontent.com/31628143/114433214-8e99ba00-9b8f-11eb-8262-093e57c1cfc7.png)
https://discord.com/channels/532476765860265984/532476765860265986/831212037681184789

**Comment by myangelaku** [comment] 2021-04-14 16:24
![Circleguard_x43R3vnzA6](https://user-images.githubusercontent.com/28674643/114745052-95226000-9d4e-11eb-9422-7306793b058e.png)
![Circleguard_a8sUoproWC](https://user-images.githubusercontent.com/28674643/114745063-981d5080-9d4e-11eb-977e-acda363760a0.png)

**Comment by tybug** [comment] 2021-04-20 03:36
closed by 3b06d06cf6fa307012ea3100a701c4780eed8559

**Closed by tybug** 2021-04-20 03:36 UTC
