### ISSUE TITLE
add ability to reorder and delete runs in Queue tab

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#141] opened 2021-04-02 13:18 UTC
Simply, sometimes i wanna check something as fast as possible, or change my mind on checking some runs, and i don't wanna cancel all of them. At least, delete option would be enough, but pause/resume would be also nice.
Or something like "change order of checking".

**Comment by myangelaku** [comment] 2021-04-02 14:55
I second this, happens to me a lot!

**Comment by tybug** [comment] 2021-04-02 17:35
Agreed this would be nice, but for the time being, can't you cancel future runs to effectively 'delete' them? Or do you means something else by a delete option?

**Comment by myangelaku** [comment] 2021-04-02 17:51
> 
> 
> Agreed this would be nice, but for the time being, can't you cancel future runs to effectively 'delete' them? Or do you mean something else by a delete option?

Indeed, but the problem is that sometimes, adding runs can be "high effort" if it means copy-pasting a beatmap ID 9 times lol

**Comment by Riddalmorning** [comment] 2021-04-02 17:59
> can't you cancel future runs to effectively 'delete' them?

I myself have forgotten what I was thinking when I wrote this, but we will rephrase it this way - instead of canceling, delete the run. It is the same with the already completed run.

**Comment by tybug** [comment] 2021-04-03 04:06
so to clarify: for runs that have already been completed or runs that you've canceled, you want them totally gone from the runs menu instead of still being there but labeled as "canceled"? I agree.

**Comment by tybug** [comment] 2021-04-13 21:51
Closed in 5afacaf9576218faad4ff96de55184d94b4a201d, 0f5d1bf1e7ff3e4a7539415db4cd78c03a46f1ed, c7cc50e27b529249ac80ebe3bd1bc33fb3e4790c (mostly this one).

To summarize: runs are removed entirely when they're canceled or when they finish. Runs are now ordered by most recently added last, so the first run is the next one to be processed. Runs can be moved up or down to adjust their order.

![image](https://user-images.githubusercontent.com/31628143/114625736-b452bc00-9c80-11eb-819f-0fb6ea99ab44.png)

**Closed by tybug** 2021-04-13 21:51 UTC
Labels: effort: medium, in progress
