### ISSUE TITLE
Using the same path for local replays folder not working after reloading loadable.

### ISSUE THREAD

**Issue by Riddalmorning** [circleguard/circleguard#108] opened 2020-12-10 12:26 UTC
For example:
1. Create "Local replay" loadable
2. Click on "Choose folder", and choose any path
3. Click "Run"
4. After this, you wanna reload loadable, so you will delete this loadable, and do same steps (1,2,3)
5. Circleguard refuses to run the scan because he doesn't like something in our loadable
![Screenshot_3](https://user-images.githubusercontent.com/75766843/101772116-60826b80-3b04-11eb-9e26-f01086e9e3dd.png)

Edit: Step 4 also applies when you close and reopen Circleguard

**Comment by tybug** [comment] 2020-12-10 16:06
I can't reproduce this. Does the path there (`C:\Users\ridda\Desktop\dench`) appear automatically when you create the loadable or do you have to select a folder manually for it to appear? 

This is probably happening because circleguard doesn't think you've changed your selection from when the loadable was created, with the intent of not letting empty loadables be allowed. As a workaround, you should be able to choose a different folder and then re-select the folder you want, and then run.

**Comment by Riddalmorning** [comment] 2020-12-10 18:17
Yes.
Circleguard remembers the last path I choose, and after clicking the "Choose folder", it suggests the last path I chose.

**Comment by tybug** [comment] 2020-12-10 18:47
should be fixed in the next release

**Closed by tybug** 2020-12-10 18:47 UTC
