### ISSUE TITLE
Replays don't load on Visualize tab

### ISSUE THREAD

**Issue by obrigadex** [circleguard/circleguard#49] opened 2019-11-23 11:47 UTC
I dont really know what im doing wrong. When i try to load a replay on Visualize, the tab doesn't change anything in it. I asked my friend that uses Circleguard and he said that it was working fine. Maybe my pc is missing something, i have no idea. Help?

![image](https://user-images.githubusercontent.com/47151609/69478128-c0697f80-0de6-11ea-98cd-28b880effc99.png)

(that print was taken after i tried to add a replay)

**Comment by tybug** [comment] 2019-11-23 12:11
Please turn debug mode to trace and debug output to new window in the settings, reproduce, and post the output here

**Comment by obrigadex** [comment] 2019-11-23 12:31
> Please turn debug mode to trace and debug output to new window in the settings, reproduce, and post the output here

![Screenshot_2](https://user-images.githubusercontent.com/47151609/69478690-1e00ca80-0ded-11ea-921c-822bfdac08ec.png)

**Comment by InvisibleSymbol** [comment] 2019-11-23 14:34
Works correctly on my end. To help us further investigate the issue, it would be nice if you could:
- Confirm that you set your output to trace, since we either aren't seeing the output or the replay can't be loaded.
- Upload the replay so we can test it on our end. This is so we can determine if your system/the replay or our program is at fault

**Comment by obrigadex** [comment] 2019-11-23 14:53
There you have. My friend tested the replay and worked fine for him, but i'll send it anyways. 
The problem can be from my laptop, it is old af.

[Replay](https://github.com/circleguard/circleguard/files/3882577/2691.zip)



![image](https://user-images.githubusercontent.com/47151609/69480624-07646e80-0e01-11ea-8415-6cc932e77335.png)

**Comment by tybug** [comment] 2019-11-24 04:14
Not sure what's happening then; loads fine for me as well. We'll hopefully have proper gui-side logging at some point instead of relying on circlecore logging and that might help figure this out. In the meantime if you figure out anything else about what replays you can't load or why, please update this issue

**Comment by obrigadex** [comment] 2019-11-24 10:30
I think i found why it doesn't load, but still can't open it. I needed to re-"install" the program, and this appeared:
![image](https://user-images.githubusercontent.com/47151609/69493319-5bc12a00-0ea5-11ea-8314-bf55ab8a4341.png)

**Comment by InvisibleSymbol** [comment] 2019-11-24 13:27
Could you tell us how you re-installed the program?

I also made a debug build that may help us with further investigation. Please try again to load the replay and send a screenshot of the windows debug terminal.
https://i.fiery.me/mPui.zip

This is an example screenshot:
![](https://i.fiery.me/R4Ki.png)

**Comment by obrigadex** [comment] 2019-11-24 13:49
When i re-installed the program I: clicked "Reset Settings", then deleted the files that i had, then unzipped the x86 (my pc is 64 bits but i did that to reset setting there too) and then deleted the files and exctracted the x64 .zip. But the first time that i unzipped the files, when i first downloaded this program, i got the same error.

![image](https://user-images.githubusercontent.com/47151609/69495642-127ed380-0ec1-11ea-92bb-0a98da197ad4.png)


ok so while i was doing this comment i got it to work. still can't see the circles nor sliders but imma try to find that out. i guess that it happened when i exctracted the x64 .zip on the x86 files.

**Comment by InvisibleSymbol** [comment] 2019-11-24 14:39
Generally mixing two different architectures is a bad idea. Also there is no real reason to reset the setting in the x86 version since they are shared (and stored somewhere else).

Most likely the reason for the original error is a wrong api key. If I modify mine to be incorrect, I can reproduce your first behavior:
![](https://i.fiery.me/2ojA.png)

I am currently in the progress of a major rewrite of our visualizer and I should be able to make it work without an api key, so issues like this won't happen again. (Beatmap visualization is still a wip, but the next release will most likely have it.)

Closing since it was resolved and there is no issue with our code.

**Closed by InvisibleSymbol** 2019-11-24 14:39 UTC

**Comment by tybug** [comment] 2019-11-30 17:07
Issue certainly seems to be either an incorrect api key, or a ratelimited api key. Ran into the latter recently.
